CREATE TABLE mas_room_group 
(id INT NOT NULL AUTO_INCREMENT, 
name TEXT NOT NULL,
created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id))
DEFAULT CHARSET=utf8;