CREATE TABLE mas_user 
(id INT NOT NULL AUTO_INCREMENT,
public_id VARCHAR(255) NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id))
DEFAULT CHARSET=utf8;
